### ISSUE TITLE
Mesh Interface Inactive after Installing with IPFS

### ISSUE THREAD

**Issue by garrying** [tomeshnet/prototype-cjdns-pi2#17]
Ran the following:
```
$ wget https://raw.githubusercontent.com/tomeshnet/prototype-cjdns-pi2/master/scripts/install && chmod +x install && WITH_IPFS=true ./install
```

Mesh Interface works fine without IPFS. Also, I haven't tried manually activing the interface after restart.

**Comment by benhylau** [comment]
I have not been able to reproduce this on a Pi 2 of 3. This seems like a rare occurrence.

**Comment by nycoliver** [comment]
May be relevant: https://github.com/ipfs/ipfs/issues/189

**Comment by claudiobizzotto** [comment]
Same thing here, @benhylau. Maybe we should just reference the issue pointed to by @nycoliver and close this one.

**Comment by benhylau** [comment]
Wait. Is it `mesh0` or `tun0` that's inactive? I thought you meant `mesh0` and that's purely 802.11s mesh point with nothing to do with cjdns.

**Comment by garrying** [comment]
It was `mesh0` being inactive. Closing this for now: I was running on a bleeding edge kernel/firmware and couldn't reproduce with stable.
