### ISSUE TITLE
Uninstall script ask before removing .ipfs

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/prototype-cjdns-pi2#24]
@claudiobizzotto Should we ask before running `rm -rf /home/pi/.ipfs` the same way **cjdroute.conf** removal is now handled?

**Comment by claudiobizzotto** [comment]
Sounds like a good idea. I haven't tested it yet, but [this](https://github.com/tomeshnet/prototype-cjdns-pi2/pull/25) should make it.
