### ISSUE TITLE
Clean up after installing ipfs

### ISSUE THREAD

**Issue by uditvira** [tomeshnet/prototype-cjdns-pi2#33]
The ipfs tarball and installation directory still exists after installation. This should be cleaned up after installation with a check to see if ipfs is working. 

`ipfs cat /ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme`

Prompt the user to see if the output looks like:

```
██║██╔══██╗██╔════╝██╔════╝
██║██████╔╝█████╗  ███████╗
██║██╔═══╝ ██╔══╝  ╚════██║
██║██║     ██║     ███████║
╚═╝╚═╝     ╚═╝     ╚══════╝

If you're seeing this, you have successfully installed
IPFS and are now interfacing with the ipfs merkledag!
```

**Comment by benhylau** [comment]
The clean up is addressed by https://github.com/tomeshnet/prototype-cjdns-pi2/pull/44
As for status check, the `status` script currently checks `ipfs-daemon.service` status, perhaps `ipfs cat /ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/readme` can be added as part of the check?

**Comment by benhylau** [comment]
Closing since cleanup is addressed and `ipfs-daemon.service` is checked
