### ISSUE TITLE
Print access point SSID after install

### ISSUE THREAD

**Issue by garrying** [tomeshnet/prototype-cjdns-pi2#45]
- Should only appear if user selects access point with install
- Might also be helpful to print their IPV6 address as well regardless if they've selected to bring up the AP

**Comment by benhylau** [comment]
How about we print SSID as part of WPA password prompt?
IPv6 is printed in `status`, is that sufficient?

**Comment by garrying** [comment]
SSID with WPA prompt: Yeah that could work.
IPv6: Maybe we can, at least, print how to get to `status` on completion.

**Comment by benhylau** [comment]
SSID with WPA prompt: f82da30572d0e4e026b7c2fe8f7e28801b5f6527
Print how to get to `status` on completion: 1a3cd3686cc8dbfd10bb7af98c7f9bdc711cd1ec
