### ISSUE TITLE
using SECCOMP for cjdns

### ISSUE THREAD

**Issue by arkgit** [tomeshnet/prototype-cjdns-pi2#47]
Does this setup run cjdns with SECCOMP disabled or does it enable in the pi?

**Comment by benhylau** [comment]
It had to be disabled: https://github.com/tomeshnet/prototype-cjdns-pi2/blob/master/scripts/install#L87

**Comment by arkgit** [comment]
You can enable seccomp in kernel and then run cjdns without disabling
seccomp

**Comment by benhylau** [comment]
That would require recompiling of the kernel
