### ISSUE TITLE
Mesh interface?

### ISSUE THREAD

**Issue by arkgit** [tomeshnet/prototype-cjdns-pi2#60]
Theres no instructions on readme about using the mesh interface

**Comment by benhylau** [comment]
If you have two then they peer up automatically and you will see each other's cjdns IP on `status`

**Comment by arkgit** [comment]
ah, thought there was more tools. /cjdns/tools has pingAll that is useful

**Comment by arkgit** [comment]
The mesh interface says its not running when running status.

Also have you ran this over two nodes connected with directional antennas?

**Comment by benhylau** [comment]
Do you have the 722N plugged in?

**Comment by arkgit** [comment]
No, using two ubiquity antennas right now

**Comment by benhylau** [comment]
Ahh, that's why the mesh interface says it's not running. You need devices that support 802.11s Mesh Point. README has more on this.

**Comment by arkgit** [comment]
Ah ok. If i add the peers manually it should work though right?

On Feb 18, 2017 9:05 AM, "Benedict Lau" <notifications@github.com> wrote:

Ahh, that's why the mesh interface says it's not running. You need devices
that support 802.11s Mesh Point. README has more on this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tomeshnet/prototype-cjdns-pi2/issues/60#issuecomment-280847618>,
or mute the thread

**Comment by benhylau** [comment]
Manually adding UDP peers, or having two devices connected to your router. Yes.
