### ISSUE TITLE
how to manually add cjdns peer

### ISSUE THREAD

**Issue by warningbagel** [tomeshnet/prototype-cjdns-pi2#62]
after using the script to install cjdns on muliple devices how does one add a peer manually so they can connect over the internet since auto peering only works on local networks

**Comment by benhylau** [comment]
For now you need to do this manually: http://home.groundupworks.com:9091/#12

Waiting on client-side for https://github.com/fc00/peers-api to become available so the process can be more user friendly.

Thanks for bringing this up!
