### ISSUE TITLE
Make script work for Pi 3

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/prototype-cjdns-pi2#7]
Because of the onboard `wlan0` on the Pi 3, the mesh script needs to bring up `wlan1` instead as the mesh link. That was the only change needed to make the install script work on Pi 3.

**Comment by garrying** [comment]
Quick thought: This issue is more to do with checking that an adapter with mesh point mode exists and using the corresponding `wlan` interface.

**Comment by benhylau** [comment]
We may as well do it right. Like you said, list supported modes and choose. Detect Pi version and pass the right `CFLAGS`, etc.

**Comment by benhylau** [comment]
https://github.com/tomeshnet/prototype-cjdns-pi2/commit/278072af44211f3813a928f98078a85729a16cc3
